# Generated by Django 2.2.2 on 2019-06-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_auto_20190617_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user',
            new_name='uploader',
        ),
    ]
