# Generated by Django 2.2.2 on 2019-06-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_file_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='firebase_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
